config/routes.rb
Rails.application.routes.draw do

  root 'shop#index'
  get 'shop/index'

  namespace :cart do
    get 'add_product/:id', controller: :product, action: :add_product, :as => 'add_product'
    get 'remove_product/:id', controller: :product, action: :remove_product, :as => 'remove_product'
    post 'add_discount', controller: :discount, action: :add_discount, :as => 'add_discount'
    get 'remove_discount/:id', controller: :discount, action: :remove_discount, :as => 'remove_discount'
    get 'check-out', controller: :check_out, action: :index, :as => 'check_out'
    get 'check-out-processing', controller: :check_out, action: :check_out, :as => 'check_out_processing'
  end

  post 'order/create', controller: :order, action: :order_creation, :as => 'order_creation'
  get  'order-confirmation/:id', controller: :order, action: :confirmation, :as => 'order_confirmation'
  get  'order/track', controller: :order, action: :track, :as => 'order_tracking' 

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord

  belongs_to :order, optional: true

  has_many :cart_discounts
  has_many :discounts, through: :cart_discounts

  has_many :cart_products
  has_many :products, through: :cart_products

  def products
    products = []
    self.cart_products.each do |association|
      product= Product.find(association.product_id)
      product.count, product.sum_price = association.count, (product.price*association.count) #virtual attributes
      products.push(product)
    end unless !self.cart_products.any?
    return products
  end

  def total_products_price
    sum = 0
    self.products.each { |a| sum+=a.sum_price}
    return sum
  end

  def total_price
    total_price = self.total_products_price
    self.discounts.order("reduction_percentage").each { |discount| total_price-=discount.reduce_amount(total_price)}
    return total_price.round(2)
  end

  def allow_discount_conjuction?(conjuction)
    return true if !self.discounts.any?
    return !conjuction ? false : self.discounts.first.conjuction
  end

  def deactivate
    self.update!(:active => false)
  end

end

app/models/cart_discount.rb
class CartDiscount < ApplicationRecord

  belongs_to :cart
  belongs_to :discount

end

app/models/cart_product.rb
class CartProduct < ApplicationRecord

  belongs_to :cart
  belongs_to :product
  
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :orders

  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }
  validates :names, length: { minimum: 3 }
  validates :card_cv_code, length: {is: 4}
  validates :card_type, presence: true
  validates :card_number, length: {in: 7..10}

end

app/models/discount.rb
class Discount < ApplicationRecord

  def reduce_amount total_price
    return self.reduction_value if !self.reduction_percentage
    return total_price*(0.01*self.reduction_value)
  end

end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :customer
  has_one :cart
  after_create :generate_key

  def generate_key
    reference = rand(2**256).to_s(36)[0..7]
    while !Order.where(:reference => reference).first.nil? do
      reference = rand(2**256).to_s(36)[0..7]
    end
    self.update(:reference => reference )
    self.save
  end

end

app/models/product.rb
class Product < ApplicationRecord
  attr_accessor :count,:sum_price

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cart/check_out_controller.rb
class Cart::CheckOutController < ShopController

  def index
    @products = @cart.products
  end

  def check_out
    @customer = Customer.new(:names => params[:names],:email => params[:email], :card_type => params[:card_type], :card_number => params[:card_number], :card_cv_code => params[:card_cv_code], :card_expiration_date => params[:card_expiration_date])
    if @customer.save
     @order = Order.create!(:customer => @customer, :cart => @cart)
     @cart.deactivate
     redirect_to order_confirmation_path(@order)
    else
      render :index
    end
  end

end

app/controllers/cart/discount_controller.rb
class Cart::DiscountController < ShopController

  def add_discount
    discount = Discount.where(:code => params[:discount_code]).first
    if !discount.nil? && (!@cart.discounts.any? || @cart.allow_discount_conjuction?(discount.conjuction)) && !@cart.discounts.include?(discount)
      @cart.discounts << discount
    end
    redirect_to root_path
  end

  def remove_discount
    @cart.discounts.delete(Discount.find(params[:id]))
    redirect_to root_path
  end

end

app/controllers/cart/product_controller.rb
class Cart::ProductController < ShopController

  def add_product
    current_product = @cart.cart_products.where(:product_id => params[:id]).first
    if current_product.nil?
      CartProduct.create(:cart => @cart, :product => Product.find(params[:id]), :count => params[:count].empty? ? 1 : params[:count] )
    else
      CartProduct.where(:cart => @cart, :product => current_product.product_id).update_all("count = count + #{params[:count]}")
    end
    redirect_to root_path
  end

  def remove_product
    current_product, count = @cart.cart_products.where(:product_id => params[:id]).first, params[:count]
    if params[:count].nil? || (current_product.count-params[:count].to_i) < 1
      @cart.cart_products.delete(current_product)
    else
      current_product.update(:count => current_product.count-params[:count].to_i)
    end
    redirect_to root_path
  end

end

app/controllers/order_controller.rb
class OrderController < ShopController

  def confirmation
    @order = Order.find(params[:id])
  end

  def track
    @order = Order.where(:reference => params[:reference]).first if !params[:reference].nil?
  end

end

app/controllers/shop_controller.rb
class ShopController < ApplicationController
  before_action :set_cart

  def index
    @products = Product.all
  end

  private
    def set_cart
      @cart = Cart.where(:active => true, :id => session[:cart_id]).first
      return if !@cart.nil?
      @cart = Cart.create!(:active => true)
      session[:cart_id] = @cart.id
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/shop_helper.rb
module ShopHelper
end

app/views/cart/cart_items_list.html.erb
<% if @cart.products.any? %>
  <table class="table table-striped table-bordered">
    <thead>
      <th></th>
      <th> <%= t "cart.quantity" %> </th>
      <th> <%= t "products.properties.name" %> </th>
      <th> <%= t "products.properties.unit_price" %> </th>
      <th> <%= t "products.properties.price" %> </th>
    <thead>
    <tbody>
      <% @cart.products.each do |product| %>
        <tr>
          <td> <%= link_to "#{ t "cart.drop" }", cart_remove_product_path(:id =>product.id, :count => nil) , :class => "btn btn-sm btn-danger" %> </td>
          <td>
            <%= product.count %>
            <%= link_to "-", cart_remove_product_path(:id => product.id, :count => 1) , :class => "btn btn-sm btn-danger" %>
            <%= link_to "+", cart_add_product_path(:id => product.id, :count => 1) , :class => "btn btn-sm btn-success" %>
          </td>
          <td> <%= product.try(:title) %> </td>
          <td> <%= product.price %> £ </td>
          <td> <%= product.sum_price %> £</td>
        <tr>
      <% end %>
    </tbody>
    <tfoot>
      <tr>
        <td colspan="3"> <%= t "cart.total_products_price" %> </td>
        <td colspan="2" class="price"> <strong><%= @cart.total_products_price %> £</strong> </td>
      </tr>
      <tr>
        <td> <p> <%= t("cart.promotions") %> </p> </td>
        <td colspan="4"> <%= render "cart/discount/form" %> </td>
      </tr>
      <% @cart.discounts.order("reduction_percentage").each do |discount| %>
        <tr>
          <td> <%= link_to t("cart.drop_discount"), cart_remove_discount_path(discount.id), :class=>"btn btn-sm" %> </td>
          <td colspan="3"> <%= discount.name %> </td>
          <td> -<%= discount.reduction_value %><%= discount.reduction_percentage ? "%" : "£"  %> </td>
        </tr>
      <% end %>
    <tfoot>
  </table>
  <%= link_to t("cart.proceed_to_checkout") ,cart_check_out_path, :class => "btn btn-warning" %>
<% else %>
  <label class="label label-primary"> <%= t "cart.no_products" %> </label>
<% end %>

app/views/cart/check_out/_customer_form.html.erb
<section>

  <% if !@customer.nil? && @customer.errors.any? %>
    <div id="error_explanation" class='error_container'>
      <% @customer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </div>
  <% end %>

  <div class="container">
    <%= form_tag cart_check_out_processing_path, :method => "GET"  do  %>
    <h4> <%= t("order.fill_fields") %> </h4>

      <div class="row">
        <div class="col-sm-6">
          <div class="form-group">
            <%= label_tag t("customer.names") %>
            <%= text_field_tag :names, params[:names], :class => "form-control" %>
            <hr>
            <%= label_tag t("customer.email") %>
            <%= email_field_tag :email, params[:email], :class => "form-control" %>
          </div>
        </div>
        <div class="col-sm-6">
          <div class="form-group">
            <div class="row">
              <div class="col-sm-4">
                <%= label_tag t("customer.card_type") %>
                <%= text_field_tag :card_type, params[:card_type], :class => "form-control" %>
              </div>
              <div class="col-sm-8">
                <%= label_tag t("customer.card_number") %>
                <%= number_field_tag :card_number, params[:card_number], :class => "form-control" %>
              </div>
            </div>
            <hr>
            <div class="row">
              <div class="col-sm-3">
                <%= label_tag t("customer.card_cv_code") %>
                <%= number_field_tag :card_cv_code,params[:card_cv_code] , :class => "form-control" %>
              </div>
              <div class="col-sm-9">
                <%= label_tag t("customer.card_expiration_date") %>
                <%= date_field_tag :card_expiration_date,params[:card_expiration_date] , :class => "form-control" %>
              </div>
            </div>

          </div>
        </div>
      </div>
      <%= submit_tag t("cart.order_confirmation"), :class => 'btn btn-success right' %>
      <%= link_to t("global.back_to_shop") ,root_path, :class => "btn btn-info"  %>
    <% end %>
  </div>
<section>

app/views/cart/check_out/_summary_table.html.erb
<% if @cart.products.any? %>
  <table class="table table-striped table-bordered">
    <thead>
      <th> <%= t "cart.quantity" %> </th>
      <th> <%= t "products.properties.name" %> </th>
      <th> <%= t "products.properties.unit_price" %> </th>
      <th> <%= t "products.properties.price" %> </th>
    <thead>
    <tbody>
      <% @cart.products.each do |product| %>
        <tr>
          <td>
            <%= product.count %> x
          </td>
          <td> <%= product.try(:title) %> </td>
          <td> <%= product.price %> £ </td>
          <td class="text-align--right"> <%= product.sum_price %> £</td>
        <tr>
      <% end %>
    </tbody>
    <tfoot>
      <tr>
        <td colspan="2"> <%= t "cart.total_products_price" %> </td>
        <td colspan="2" class="price"> <strong><%= @cart.total_products_price %> £</strong> </td>
      </tr>
      <% @cart.discounts.order("reduction_percentage").each do |discount| %>
        <tr class="bordered">
          <td colspan="3"> <%= discount.name %> </td>
          <td class="text-align--right"> -<%= discount.reduction_value %><%= discount.reduction_percentage ? "%" : "£"  %> </td>
        </tr>
      <% end %>
      <tr>
        <td colspan="3"> <%= t "cart.total_price" %> </td>
        <td colspan="2" class="price total"> <strong><%= @cart.total_price %> £</strong> </td>
      </tr>
    <tfoot>
  </table>
<% else %>
  <label class="label label-primary"> <%= t "cart.no_products" %> </label>
<% end %>

app/views/cart/check_out/index.html.erb
<section>
  <div class="container">
    <div class="row">
      <div class="col-sm-12">
        <h1 class="text-align--center"> <%= t "cart.check_out" %> </h1>
        <%= render 'summary_table' %>
        <%= render 'customer_form' %>
      </div>
    </div>
  </div>
</section>

app/views/cart/discount/_form.html.erb
<%= form_tag cart_add_discount_path, :class=>"inliner form-inline" do %>
  <%= text_field_tag :discount_code, "", :class=>"form-control" ,:placeholder => t("cart.enter_code") %>
  <%= submit_tag t("cart.add_discount"), :class => "btn btn-sm btn-info"   %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NeosCheckout</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/order/confirmation.html.erb
<section>

  <div class="container">
    <div class="row">

      <div class="col-sm-12">
        <p class="alert alert-success"> <%= t("order.just_generated", :reference => @order.reference).html_safe %> <%= t("order.save_reference") %> </p>
        <%= render :template => 'order/show' %>
      </div>

    </div>
  </div>

</section>

app/views/order/show.html.erb
<table class="table table-striped table-bordered">
  <thead>
    <th> <%= t "cart.quantity" %> </th>
    <th> <%= t "products.properties.name" %> </th>
    <th> <%= t "products.properties.unit_price" %> </th>
    <th> <%= t "products.properties.price" %> </th>
  <thead>
  <tbody>
    <% @order.cart.products.each do |product| %>
      <tr>
        <td>
          <%= product.count %> x
        </td>
        <td> <%= product.try(:title) %> </td>
        <td> <%= product.price %> £ </td>
        <td class="text-align--right"> <%= product.sum_price %> £</td>
      <tr>
    <% end %>
  </tbody>
  <tfoot>
    <tr>
      <td colspan="2"> <%= t "cart.total_products_price" %> </td>
      <td colspan="2" class="price"> <strong><%= @order.cart.total_products_price %> £</strong> </td>
    </tr>
    <% @order.cart.discounts.order("reduction_percentage").each do |discount| %>
      <tr class="bordered">
        <td colspan="3"> <%= discount.name %> </td>
        <td class="text-align--right"> -<%= discount.reduction_value %><%= discount.reduction_percentage ? "%" : "£"  %> </td>
      </tr>
    <% end %>
    <tr>
      <td colspan="3"> <%= t "cart.total_price" %> </td>
      <td colspan="2" class="price total"> <strong><%= @order.cart.total_price %> £</strong> </td>
    </tr>
  <tfoot>
</table>
<h5> <%= t("customer.details") %> </h5>
<hr>

<div class="box cutomer__container">
  <div class="row">
    <div class="col-sm-6">
      <p> <strong><%= t("customer.names") %></strong>: <%= @order.customer.names %> </p>
      <p> <strong><%= t("customer.email") %></strong>: <%= @order.customer.email %> </p>
    </div>
    <div class="col-sm-6">
      <div class="row">
        <div class="col-sm-6">
          <p> <strong><%= t("customer.card_type") %></strong>: <%= @order.customer.card_type %> </p>
          <p> <strong><%= t("customer.card_number") %></strong>: <%= @order.customer.card_number %> </p>
        </div>
        <div class="col-sm-6">
          <p> <strong><%= t("customer.card_expiration_date") %></strong>: <%= @order.customer.card_expiration_date %> </p>
          <p> <strong><%= t("customer.card_cv_code") %></strong>: <%= @order.customer.card_cv_code %> </p>
        </div>
      </div>

    </div>
  </div>

</div>

<%= link_to t("global.back_to_shop") ,root_path, :class => "btn btn-info"  %>

app/views/order/track.html.erb
<section>

  <div class="container">
    <div class="row">

      <div class="col-sm-12">
        <h3> <%= t("order.tracking") %> </h3>
        <%= form_tag "", :method => "GET" ,:class => "form-inline" do  %>
          <%= text_field_tag :reference, params[:reference], :class => "form-control", :placeholder => t("order.enter_reference") %>
          <%= submit_tag t("order.track"), :class => "btn btn-success" %>
        <% end %>

        <% if !@order.nil? %>
          <hr>
          <%= render :template => 'order/show' %>
        <% end %>
      </div>

    </div>
  </div>

</section>

app/views/shop/_product_list.html.erb
<table class="table table-striped table-bordered">
  <thead>
    <th> <%= t "products.properties.name" %> </th>
    <th> <%= t "products.properties.price" %> </th>
    <th></th>
  <thead>
  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td> <%= product.try(:title) %> </td>
        <td> <%= product.price %> £ </td>
        <td>
          <%= form_tag cart_add_product_path(product.id), :method => "GET" do  %>
            <div class="inliner">
              <p><%= t "cart.quantity" %></p>
              <%= number_field_tag :count, 1 , :class => "", :min => 1 %>
            </div>
            <%= submit_tag "#{ t "products.add_to_cart" }", :class => "btn btn-sm btn-success" %>
          <% end %>
        </td>
      <tr>
    <% end %>
  </tbody>
</table>

app/views/shop/index.html.erb
<section>
  <div class="container">
    <div class="row">
      <div class="col-sm-6">
        <h1 class="text-align--center"> <%= t "products.avaiable" %> </h1>
        <%= render 'product_list' %>
        <%= link_to t("order.tracking"), order_tracking_path, :class => "btn btn-info" %>
      </div>
      <div class="col-sm-6">
        <h1 class="text-align--center"> <%= t "cart.your_cart" %> </h1>
        <%= render :template => 'cart/cart_items_list' %>
      </div>
    </div>
  </div>
</section>